name: build

on: 
  workflow_dispatch:
  push:

jobs:
    install:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        - name: Cache dependencies
          id: node-modules-cache
          uses: actions/cache@v2
          with:
            path: ./node_modules
            key: modules-${{ hashFiles('package-lock.json') }}

        - name: Install dependencies
          run: cd ./node_modules || npm ci

    prettier:
      needs: [install]
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2 
        - name: Cache dependencies
          id: node-modules-cache
          uses: actions/cache@v2
          with:
            path: ./node_modules
            key: modules-${{ hashFiles('package-lock.json') }}
        - name: Format check
          run: npm run prettier

    compile:
      needs: [install]
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2 
        - name: Cache dependencies
          id: node-modules-cache
          uses: actions/cache@v2
          with:
            path: ./node_modules
            key: modules-${{ hashFiles('package-lock.json') }}
        - name: TS Compile
          run: npm run tsc

    test:
      needs: [install]
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2 
        - name: Cache dependencies
          id: node-modules-cache
          uses: actions/cache@v2
          with:
            path: ./node_modules
            key: modules-${{ hashFiles('package-lock.json') }}
        - name: Tests
          run: npm run coverage